package Formularios;

import Entidades.DespachoDetalle;
import Entidades.View_ReporteDespacho;
import Entidades.View_ReporteSolicitudRepuesto;
import static Formularios.FrmDespacho.DEST;
import Logico.SolicitudRepuestoDetalleLog;
import Logico.View_ReporteDespachoLog;
import Logico.View_ReporteSolicitudRepuestoLog;
import ModeloTabla.CmbUnidad;
import ModeloTabla.ModeloTablaView_ReporteDespacho;
import ModeloTabla.ModeloTablaView_ReporteSolicitudRepuesto;

import Entidades.DespachoDetalle;
import Logico.DespachoDetalleLog;
import ModeloTabla.ModeloTablaDespachoDetalle;

import clases.Datos;

import clases.Inventario;
import clases.Render;
import com.itextpdf.text.Document;
import com.itextpdf.text.Font;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.*;
import java.util.TreeMap;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import org.apache.poi.hwpf.model.FileInformationBlock;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.IndexedColors;
import org.apache.poi.xssf.usermodel.XSSFCellStyle;
import org.apache.poi.xssf.usermodel.XSSFDataFormat;

public class FrmInformeReporteDespacho extends javax.swing.JInternalFrame {

    View_ReporteDespacho obxdatos;
    View_ReporteDespachoLog claselog;
    ModeloTablaView_ReporteDespacho modelo;
    
    DespachoDetalleLog cl_despachodetalle_log;
    DespachoDetalle cl_despachodetalle;
    ModeloTablaDespachoDetalle mt_dd;
    
    public FrmInformeReporteDespacho() {
        initComponents();
        int id_usuario = Integer.parseInt(Inventario.global_llaveusuario);
        
        cl_despachodetalle_log = new DespachoDetalleLog();
        
        claselog = new View_ReporteDespachoLog();
        
        ListarTabla();
    }
    
    private void ListarTabla() {
                
        List<View_ReporteDespacho> listas = claselog.listado();
        modelo = new ModeloTablaView_ReporteDespacho
        (
                listas
        )
        {
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        
        jTable1.setDefaultRenderer(Object.class, new Render());
        JButton btn1 = new JButton("Imprimir");
        
        jTable1.setModel(modelo);
        jTable1.setRowHeight(30);
        
        jTable1.getRowSorter();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlgrid = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        pnlgrid.setBorder(javax.swing.BorderFactory.createTitledBorder("SOLICITUD DESPACHOS"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout pnlgridLayout = new javax.swing.GroupLayout(pnlgrid);
        pnlgrid.setLayout(pnlgridLayout);
        pnlgridLayout.setHorizontalGroup(
            pnlgridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlgridLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlgridLayout.setVerticalGroup(
            pnlgridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlgridLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlgrid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlgrid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        obxdatos = ((ModeloTablaView_ReporteDespacho) jTable1.getModel()).DameDespachoDetalle(jTable1.getSelectedRow());
        
        int llave = obxdatos.getIdDespacho();
        String stxunidad  = obxdatos.getUnidad();
        String id_comercio = obxdatos.getIdComercial();
       
        
        int column = jTable1.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY()/jTable1.getRowHeight();
        
        if(row < jTable1.getRowCount() && row >= 0 && column < jTable1.getColumnCount() && column >= 0) {
            Object value = jTable1.getValueAt(row, column);
            if(value instanceof JButton){
                ((JButton)value).doClick();
                generar_pdf(llave, stxunidad, id_comercio);
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    public void generar_pdf(int llavedespacho, String stx_unidad, String id_comercio)
    {
        try {
            
            String DEST = "c:/excel/ReporteDespacho_";
            
            Rectangle small = new Rectangle(290,100);
            Font smallfont = new Font(Font.FontFamily.HELVETICA, 6);
            Font mediumfont = new Font(Font.FontFamily.HELVETICA, 8);
            Font largefont = new Font(Font.FontFamily.HELVETICA, 10);

            FileOutputStream archivo = new FileOutputStream(DEST + id_comercio +".pdf");
            Document doc = new Document(PageSize.LETTER);
            PdfWriter.getInstance(doc, archivo);
            doc.open();


            Paragraph paragraph1 = new Paragraph("Despacho de Materiales SAV Nº " + id_comercio + " " + stx_unidad, largefont);
            paragraph1.setSpacingBefore(20f);
            doc.add(paragraph1);

            paragraph1 = new Paragraph("Se realiza despacho de los siguientes materiales a la unidad de " + stx_unidad, mediumfont);
            paragraph1.setSpacingBefore(20f);
            doc.add(paragraph1);

            paragraph1 = new Paragraph("PRIORIDAD DEL DESPACHO : NORMAL", mediumfont);
            paragraph1.setSpacingBefore(20f);
            doc.add(paragraph1);

            paragraph1 = new Paragraph(" ", mediumfont);
            paragraph1.setSpacingBefore(20f);
            doc.add(paragraph1);

            PdfPTable table = new PdfPTable(5);
            table.setTotalWidth(new float[]{ 80, 100,160,100,80});
            table.setLockedWidth(true);

            PdfPCell cell = new PdfPCell(new Phrase("S.N.S", mediumfont));
            cell.setFixedHeight(20);
            table.addCell(cell);

            cell = new PdfPCell(new Phrase("PRODUCTO", mediumfont));
            cell.setFixedHeight(20);
            table.addCell(cell);

            cell = new PdfPCell(new Phrase("DESCRIPCION", mediumfont));
            cell.setFixedHeight(20);
            table.addCell(cell);

            cell = new PdfPCell(new Phrase("Nº PARTE", mediumfont));
            cell.setFixedHeight(20);
            table.addCell(cell);

            cell = new PdfPCell(new Phrase("CANTIDAD DESPACHO", mediumfont));
            cell.setFixedHeight(20);
            table.addCell(cell);    

            //SECOND ROW

            List<DespachoDetalle> listas = cl_despachodetalle_log.listado(llavedespacho);

            for(DespachoDetalle despacho : listas){
                cell = new PdfPCell(new Phrase(despacho.getNsn(), smallfont));
                table.addCell(cell);
                cell = new PdfPCell(new Phrase(despacho.getProduto(), smallfont));
                table.addCell(cell);
                cell = new PdfPCell(new Phrase(despacho.getDescripcion(), smallfont));
                table.addCell(cell);
                cell = new PdfPCell(new Phrase(despacho.getNumeroparte(), smallfont));
                table.addCell(cell);
                cell = new PdfPCell(new Phrase(String.valueOf(despacho.getCantidad()), smallfont));
                table.addCell(cell);
            }
            doc.add(table);

            doc.close();
            /*JOptionPane.showMessageDialog(null, "PDF correctamente Creado");*/
            
            File path = new File (DEST + id_comercio +".pdf");
            Desktop.getDesktop().open(path);
        
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel pnlgrid;
    // End of variables declaration//GEN-END:variables
}
